config/routes.rb
Catalogodigital::Application.routes.draw do
  resources :productos

  resources :categoria

  get "welcome/index"

  devise_for :users, :path_names => { :sign_up => "registro" }
  resources :catalogos

  root :to => 'productos#new'

end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
  belongs_to :user	
  has_many :categoriums

  attr_accessible :direccion_rapida, :nombre, :user_id
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
  belongs_to :catalogo
  has_many :productos
  attr_accessible :catalogo_id, :descripcion, :nombre
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :categorium
  attr_accessible :categoria_id, :codigo, :descripcion, :nombre, :precio, :catalogo_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :catalogos

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :nombre, :telefono, :industria, :pais, :codigo_especial
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/catalogos_controller.rb
class CatalogosController < ApplicationController
  # GET /catalogos
  # GET /catalogos.json

  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @catalogos = Catalogo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @catalogos }
    end
  end

  # GET /catalogos/1
  # GET /catalogos/1.json
  def show
    @catalogo = Catalogo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @catalogo }
    end
  end

  # GET /catalogos/new
  # GET /catalogos/new.json
  def new
    @catalogo = Catalogo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @catalogo }
    end
  end

  # GET /catalogos/1/edit
  def edit
    @catalogo = Catalogo.find(params[:id])
  end

  # POST /catalogos
  # POST /catalogos.json
  def create
    @catalogo = Catalogo.new(params[:catalogo])
    @catalogo.user = current_user;

    respond_to do |format|
      if @catalogo.save
        format.html { redirect_to @catalogo, notice: 'Catalogo was successfully created.' }
        format.json { render json: @catalogo, status: :created, location: @catalogo }
      else
        format.html { render action: "new" }
        format.json { render json: @catalogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /catalogos/1
  # PUT /catalogos/1.json
  def update
    @catalogo = Catalogo.find(params[:id])

    respond_to do |format|
      if @catalogo.update_attributes(params[:catalogo])
        format.html { redirect_to @catalogo, notice: 'Catalogo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @catalogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogos/1
  # DELETE /catalogos/1.json
  def destroy
    @catalogo = Catalogo.find(params[:id])
    @catalogo.destroy

    respond_to do |format|
      format.html { redirect_to catalogos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  # GET /categoria
  # GET /categoria.json

  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @categoria = Categorium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
    @categorium = Categorium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categorium }
    end
  end

  # GET /categoria/new
  # GET /categoria/new.json
  def new
    @categorium = Categorium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categorium }
    end
  end

  # GET /categoria/1/edit
  def edit
    @categorium = Categorium.find(params[:id])
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(params[:categorium])
    
    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render json: @categorium, status: :created, location: @categorium }
      else
        format.html { render action: "new" }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categoria/1
  # PUT /categoria/1.json
  def update
    @categorium = Categorium.find(params[:id])

    respond_to do |format|
      if @categorium.update_attributes(params[:categorium])
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium = Categorium.find(params[:id])
    @categorium.destroy

    respond_to do |format|
      format.html { redirect_to categoria_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.json

  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @productos = Producto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/catalogos/_form.html.erb
<%= form_for(@catalogo) do |f| %>
  <% if @catalogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@catalogo.errors.count, "error") %> prohibited this catalogo from being saved:</h2>

      <ul>
      <% @catalogo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion_rapida %><br />
    <%= f.text_field :direccion_rapida %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/catalogos/edit.html.erb
<h1>Editing catalogo</h1>

<%= render 'form' %>

<%= link_to 'Show', @catalogo %> |
<%= link_to 'Back', catalogos_path %>

app/views/catalogos/index.html.erb
<h1>Listing catalogos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Direccion rapida</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @catalogos.each do |catalogo| %>
  <tr>
    <td><%= catalogo.nombre %></td>
    <td><%= catalogo.direccion_rapida %></td>
    <td><%= catalogo.user_id %></td>
    <td><%= link_to 'Show', catalogo %></td>
    <td><%= link_to 'Edit', edit_catalogo_path(catalogo) %></td>
    <td><%= link_to 'Destroy', catalogo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Catalogo', new_catalogo_path %>

app/views/catalogos/new.html.erb
<h1>New catalogo</h1>

<%= render 'form' %>

<%= link_to 'Back', catalogos_path %>

app/views/catalogos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @catalogo.nombre %>
</p>

<p>
  <b>Direccion rapida:</b>
  <%= @catalogo.direccion_rapida %>
</p>

<p>
  <b>User:</b>
  <%= @catalogo.user_id %>
</p>

<p>
	<%= link_to('Agregar un producto', new_producto_path(:catalogo_id => @catalogo.id ) ) %>
</p>


<%= link_to 'Edit', edit_catalogo_path(@catalogo) %> |
<%= link_to 'Back', catalogos_path %>

app/views/categoria/_form.html.erb
<%= form_for(@categorium) do |f| %>
  <% if @categorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
      <% @categorium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>

  <%= f.hidden_field :catalogo_id, :value => params[:catalogo_id] %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoria/edit.html.erb
<h1>Editing categorium</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorium %> |
<%= link_to 'Back', categoria_path %>

app/views/categoria/index.html.erb
<h1>Listing categoria</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Catalogo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categoria.each do |categorium| %>
  <tr>
    <td><%= categorium.nombre %></td>
    <td><%= categorium.descripcion %></td>
    <td><%= categorium.catalogo_id %></td>
    <td><%= link_to 'Show', categorium %></td>
    <td><%= link_to 'Edit', edit_categorium_path(categorium) %></td>
    <td><%= link_to 'Destroy', categorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categorium', new_categorium_path %>

app/views/categoria/new.html.erb
<h1>New categorium</h1>

<%= render 'form' %>

<%= link_to 'Back', categoria_path %>

app/views/categoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @categorium.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @categorium.descripcion %>
</p>

<p>
  <b>Catalogo:</b>
  <%= @categorium.catalogo_id %>
</p>


<%= link_to 'Edit', edit_categorium_path(@categorium) %> |
<%= link_to 'Back', categoria_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Catalogodigital" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Catalogodigital</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/productos/_form.html.erb
<%= form_for @producto, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :codigo, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :codigo, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :precio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :precio, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descripcion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :categoria_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :categoria_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :catalogo_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :catalogo_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                productos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/productos/index.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:codigo) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:precio) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:categoria_id) %></th>
      <th><%= model_class.human_attribute_name(:catalogo_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= link_to producto.id, producto_path(producto) %></td>
        <td><%= producto.codigo %></td>
        <td><%= producto.nombre %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.categoria_id %></td>
        <td><%= producto.catalogo_id %></td>
        <td><%=l producto.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_producto_path(producto), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      producto_path(producto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_producto_path,
            :class => 'btn btn-primary' %>

app/views/productos/new.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/productos/show.html.erb
<%- model_class = Producto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:codigo) %>:</strong></dt>
  <dd><%= @producto.codigo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @producto.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precio) %>:</strong></dt>
  <dd><%= @producto.precio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @producto.descripcion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:categoria_id) %>:</strong></dt>
  <dd><%= @producto.categoria_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:catalogo_id) %>:</strong></dt>
  <dd><%= @producto.catalogo_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              productos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_producto_path(@producto), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              producto_path(@producto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>